ARG CC65_VERSION=2.19
ARG CC65_ROOT=/opt/cc65

FROM alpine:latest AS build

ARG CC65_VERSION
ARG CC65_ROOT

RUN apk add --update --no-cache gcc make musl-dev

WORKDIR /usr/src

RUN wget https://github.com/cc65/cc65/archive/V${CC65_VERSION}.zip -O cc65-${CC65_VERSION}.zip \
  && unzip cc65-${CC65_VERSION}.zip \
  && cd cc65-${CC65_VERSION} \
  && make PREFIX=$CC65_ROOT LDFLAGS="-s" \
  && make PREFIX=$CC65_ROOT install

FROM alpine:latest

ARG CC65_ROOT

RUN apk add --update --no-cache make

COPY --from=build $CC65_ROOT $CC65_ROOT

ENV PATH $CC65_ROOT/bin:$PATH
WORKDIR /workdir
